import Link from "next/link";
import Image from "next/image";
import { agent } from "@/lib/data";
import { Instagram, Mail, MessageCircle } from "lucide-react";
export default function Footer(){return <footer className="footer"><div className="footer-grid">
  <div><div className="brand footer-brand"><span className="footer-profile"><Image src="/agent-profile.png" alt="Mona Meenakshi" width={58} height={58}/></span><span><b>Mona Meenakshi</b><small>REALTOR® · DRE #02097374</small></span></div><p>Thoughtful guidance for buyers, sellers and investors across California&apos;s Central Valley.</p></div>
  <div><h3>Explore</h3><Link href="/property">Listings</Link><Link href="/about">About Mona</Link><Link href="/testimonials">Verified reviews</Link><Link href="/contactus">Contact</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of use</Link><Link href="/accessibility">Accessibility</Link><Link href="/fair-housing">Fair housing</Link></div>
  <div><h3>Connect</h3><a href={`tel:${agent.phoneHref}`}>{agent.phone}</a><a href={`mailto:${agent.email}`}>{agent.email}</a><div className="social-row"><a href={`mailto:${agent.email}`} aria-label="Email Mona" title="Email"><Mail/></a><a href={`https://wa.me/${agent.phoneHref.replace("+","")}`} target="_blank" rel="noreferrer" aria-label="WhatsApp Mona" title="WhatsApp"><MessageCircle/></a><a href={agent.instagram} target="_blank" rel="noreferrer" aria-label="Instagram" title="Instagram"><Instagram/></a><a href={agent.tiktok} target="_blank" rel="noreferrer" aria-label="TikTok" title="TikTok"><span className="social-text">T</span></a></div></div>
  <div><h3>Office</h3><p><a className="brokerage-link" href={agent.brokerageUrl} target="_blank" rel="noreferrer">{agent.brokerage} ↗</a><br/>{agent.office}<br/>{agent.license}</p><a href={agent.crmLogin} target="_blank" rel="noreferrer">Agent CRM login ↗</a></div>
</div><div className="footer-bottom"><a className="timex-credit" href="https://timexsolutioninc.com/" target="_blank" rel="noreferrer"><small>DESIGNED &amp; DEVELOPED BY</small><b>Timex Solutions Inc</b></a><span>© {new Date().getFullYear()} Mona Meenakshi · Each office is independently owned and operated. · REALTOR® · {agent.license} · Equal Housing Opportunity</span><div className="legal-links"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/accessibility">Accessibility</Link><Link href="/fair-housing">Fair Housing</Link></div></div></footer>}
