import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Languages, MapPin, MoveRight, MessageCircle, Home as HomeIcon, KeyRound, TrendingUp, LogIn, Star } from "lucide-react";
import FeaturedListingsCarousel from "@/components/shared/FeaturedListingsCarousel";
import PortfolioOverview from "@/components/shared/PortfolioOverview";
import Reveal from "@/components/shared/Reveal";
import { agent, serviceAreas } from "@/lib/data";
import { getListings } from "@/lib/mls";

export default async function Home(){const listings=await getListings();return <>
  <section className="ref-hero"><div className="ref-shell"><div className="ref-hero-top"><div className="hero-arrow"><ArrowRight/></div><h1>Future of<br/>Valley <em>living.</em></h1><Image className="house-cutout" src="/luxury-house-cutout.png" alt="Conceptual modern home" width={1000} height={520} priority/><p>Mona connects people, property and possibility through thoughtful local representation.</p></div><div className="ref-photo"><Image src="/luxury-central-valley-hero.png" alt="Conceptual modern luxury residence in California" fill priority sizes="(max-width: 900px) 94vw, 88vw"/><div className="ref-photo-label"><span>Central Valley</span><b>Modern living, thoughtfully represented.</b></div><div className="agent-float"><Image src="/agent-profile.png" alt="Mona Meenakshi" width={64} height={64}/><div><small>YOUR LOCAL REALTOR®</small><b>Mona Meenakshi</b><span>{agent.license}</span></div></div></div><div className="ref-hero-foot"><div><span>01</span><b>Fresno · Clovis · Madera</b></div><div className="hero-actions"><Link href="/property" className="button black">Explore properties <ArrowRight size={18}/></Link><Link href="/contactus" className="button outline-dark">Speak with Mona</Link><a href={agent.crmLogin} target="_blank" rel="noreferrer" className="button crm-button"><LogIn size={17}/> Agent CRM Login</a></div></div></div></section>
  <section className="ticker" aria-label="Central Valley service areas"><div className="ticker-track">{[...serviceAreas,...serviceAreas].map((x,i)=><span key={`${x}-${i}`} aria-hidden={i>=serviceAreas.length}>{x}<i>✦</i></span>)}</div></section>
  <section className="section featured-section"><Reveal><div className="section-heading"><div><p className="eyebrow dark">CURATED OPPORTUNITIES</p><h2>Featured properties</h2></div><Link href="/property" className="text-link">View all listings <MoveRight/></Link></div></Reveal><FeaturedListingsCarousel listings={listings}/><p className="data-note">Listing availability and details are subject to change. Contact Mona to verify current status.</p></section>
  <PortfolioOverview listings={listings}/>
  <section className="split-section"><div className="portrait-panel"><Image src="/property/4/1.png" alt="Central Valley home represented by Mona Meenakshi" fill sizes="(max-width: 800px) 100vw, 45vw"/><div className="image-caption"><span>Central Valley living</span><b>Guidance that feels local.</b></div></div><Reveal className="split-copy"><p className="eyebrow">YOUR ADVOCATE, START TO FINISH</p><h2>Local insight.<br/>Straight answers.</h2><p>Mona helps Central Valley buyers, sellers and investors make confident decisions with steady communication and careful attention to the details that move a transaction forward.</p><ul><li><Check/>Residential, land and commercial experience</li><li><Languages/>Service in English, Hindi, Punjabi and Urdu</li><li><MapPin/>Fresno, Clovis, Madera and surrounding communities</li></ul><Link href="/about" className="button gold">Meet Mona <ArrowRight size={18}/></Link></Reveal></section>
  <section className="expertise-ribbon" aria-label="Mona Meenakshi real estate services"><div className="expertise-track">{[0,1].map(copy=><div className="expertise-set" key={copy} aria-hidden={copy===1}><span>RESIDENTIAL</span><i>✦</i><span>LAND</span><i>✦</i><span>COMMERCIAL</span><i>✦</i><span>MULTILINGUAL SERVICE</span><i>✦</i><span>CENTRAL VALLEY</span><i>✦</i></div>)}</div></section>
  <section className="journey"><Reveal><div className="journey-heading"><div><p className="eyebrow dark">HOW MONA CAN HELP</p><h2>One advisor.<br/><em>Every move.</em></h2></div><p>Strategy, representation and local knowledge—shaped around your goals, never a template.</p></div></Reveal><div className="journey-grid"><Link href="/contactus" className="journey-card"><span className="journey-number">01</span><span className="journey-icon"><KeyRound/></span><div><small>FOR BUYERS</small><h3>Buy with clarity</h3><p>Understand the market, tour the right homes and make a confident offer.</p></div><MoveRight className="journey-arrow"/></Link><Link href="/contactus" className="journey-card featured"><span className="journey-number">02</span><span className="journey-icon"><HomeIcon/></span><div><small>FOR SELLERS</small><h3>Sell with purpose</h3><p>Position, present and market your property for the strongest possible result.</p></div><MoveRight className="journey-arrow"/></Link><Link href="/property" className="journey-card"><span className="journey-number">03</span><span className="journey-icon"><TrendingUp/></span><div><small>FOR INVESTORS</small><h3>Invest wisely</h3><p>Explore residential, commercial and land opportunities across the Valley.</p></div><MoveRight className="journey-arrow"/></Link></div></section>
  <section className="review-spotlight"><div className="review-score"><span>VERIFIED CLIENT REVIEW</span><b>5.0</b><div>{[1,2,3,4,5].map(x=><Star key={x} fill="currentColor"/>)}</div><small>Realtor.com · September 2024</small></div><div className="review-quote"><p className="eyebrow">TRUST, DOCUMENTED</p><h2>Care that carries<br/><em>through closing.</em></h2><p>Mona&apos;s verified buyer review highlights responsive guidance through escrow, paperwork and the search for the right Riverstone home.</p><div><a href={agent.realtorProfile} target="_blank" rel="noreferrer" className="button gold">Read verified review <ArrowRight size={18}/></a><Link href="/testimonials" className="text-link">Review experience <MoveRight/></Link></div></div></section>
  <section className="cta-band"><div className="cta-kicker"><span>PRIVATE CONSULTATION</span><p className="eyebrow">LET&apos;S MAKE A MOVE</p><h2>Great moves begin with a real conversation.</h2></div><div className="cta-copy"><p>Share what you&apos;re looking for. Mona will respond with local insight, clear next steps and no pressure.</p><div className="cta-actions"><Link href="/contactus" className="button light">Schedule a consultation <ArrowRight size={18}/></Link><a href={`https://wa.me/${agent.phoneHref.replace("+","")}`} target="_blank" rel="noreferrer" className="button cta-whatsapp-button"><MessageCircle size={17}/> WhatsApp Mona</a></div><small>Direct, confidential and personally handled by Mona.</small></div></section>
</>}
